export const layout = { brand: "Top Traders Funding" };

export const general = {
    brand: "Top Traders Funding",
    brandLogo: "Top Traders Funding",
    locale: "فارسی",
    add: "افزودن",
    edit: "ویرایش",
    remove: "حذف",
    view: "نمایش",
    search: "جستجو",
    cancel: "لغو",
    back: "بازگشت",
    first: "اولین",
    previous: "قبلی",
    next: "بعدی",
    last: "آخرین",
    records: "رکورد",
    actions: "عملیات",
    yes: "بله",
    no: "خیر",
    submit: "ثبت",
    reset: "ریست",
    administrator: "مدیر",
    user: "کاربر",
    up: "بالا",
    down: "پایین",
    file: "فایل ضمیمه",
    itemNotFound: "آیتم یافت نشد.",
    noDataFound: "داده‌ای برای نمایش وجود ندارد.",
    noPermission: "شما مجوز ورود به این بخش را ندارید.",
    loading: "لطفا منتظر بمانید ...",
    submitLoading: "لطفا صبر کنید ...",
    networkError: "خطا در دریافت اطلاعات از سرور",
    fallbackError: "خطایی در نمایش صفحه مورد نظر رخ داد.",
    fallbackReturnHome: "بازگشت به داشبورد مدیریت",
    copiedToClipboard: ":item کپی شد!",
    dependants: "افراد تحت تکفل",
    depositSlip: "فیش واریزی",
};

export const utils = {
    notValidJson: "فایل دریافتی نامعتبر است.",
};

export const validation = {
    stringMessage: ":field تنها باید شامل حروف باشد.",
    numberMessage: ":field تنها باید شامل اعداد باشد.",
    asciiStringMessage: ":field تنها باید شامل حروف انگلیسی باشد.",
    requiredMessage: "لطفا :field را وارد نمایید.",
    validMessage: "لطفا :field را به درستی وارد نمایید.",
    confirmedMessage: ":field با تاییدیه اش مطابقت نمی نماید.",
    emailMessage: "پست الکترونیک نامعتبر است.",
    minMessage: "حداقل طول فیلد :field، :min حرف است.",
    maxMessage: "حداکثر طول فیلد :field، :max حرف است.",
    minDigitMessage: "حداقل طول فیلد :field، :min رقم است.",
    maxDigitMessage: "حداکثر طول فیلد :field، :max رقم است.",
    exactDigitMessage: "طول فیلد :field، :digit رقم است.",
    betweenDigitsMessage:
        "طول فیلد :field، حداقل :digit1 و حداکثر :digit2 رقم است.",
    minNumberMessage: "حداقل مقدار فیلد :field، باید :min باشد.",
    maxNumberMessage: "حداکثر مقدار فیلد :field، باید :max باشد.",
};

export const header = {
    chooseLocale: "انتخاب زبان",
    us: "English",
    fa: "فارسی",
    tools: "امکانات",
    changePassword: "تغییر کلمه عبور",
    profile: "پروفایل کاربری",
    logout: "خروج از حساب کاربری",
    messageInbox: "پیام",
    supportTickets: "تیکت‌ها",
};

export const footer = {
    text: "Copyright © Top Traders Funding",
    version: "داشبورد Top Traders Funding - نسخه: 1.0.0",
};

export const notAuthPages = {
    _title: "حساب اینترنتی مطمئن برای نگهداری دارایی شما",
    _subTitle:
        "با سامانه کیف پول من خرید و فروش و دارایی های دیجیتال خود را به آسانی مدیریت کنید.",
};

export const loginUserPage = {
    _title: "ورود به حساب کاربری",
    _subTitle:
        "برای استفاده از امکانات Top Traders Funding وارد حساب کاربری خود شوید.",
    username: "نام کاربری",
    usernamePlaceholder: "نام کاربری",
    password: "کلمه عبور",
    passwordPlaceholder: "کلمه عبور",
    forgot: "کلمه عبور خود را فراموش کرده‌اید؟",
    recoverPassword: "بازیابی کلمه عبور",
    notSignedup: "حساب کاربری ندارید؟",
    signup: "ثبت‌نام کنید",
    submit: "ورود به داشبورد مدیریت",
    loginByGoogle: "ورود با Google",
};

export const forgotPasswordPage = {
    _title: "بازیابی کلمه عبور",
    _subTitle: "برای بازیابی کلمه عبور، لطفا پست الکترونیک خود را وارد نمایید.",
    email: "پست الکترونیک",
    emailPlaceholder: "پست الکترونیک",
    submit: "بازیابی کلمه عبور",
    login: "ورود به داشبورد مدیریت",
    submitted: "کلمه عبور جدید به پست الکترونیک شما ارسال شد.",
};

export const signupPage = {
    _title: "ثبت نام",
    _subTitle:
        "برای افتتاح حساب در Top Traders Funding، لطفا مشخصات خود را وارد نمایید.",
    username: "نام کاربری",
    usernamePlaceholder: "نام کاربری",
    email: "پست الکترونیک",
    emailPlaceholder: "پست الکترونیک",
    password: "کلمه عبور",
    passwordPlaceholder: "کلمه عبور",
    confirmPassword: "تکرار کلمه عبور",
    confirmPasswordPlaceholder: "تکرار کلمه عبور",
    name: "نام",
    namePlaceholder: "نام",
    family: "نام خانوادگی",
    familyPlaceholder: "نام خانوادگی",
    submit: "ثبت‌نام",
    haveAccount: "حساب کاربری دارید؟",
    login: "ورود به داشبورد مدیریت",
};

export const sidebar = {
    mainMenu: "منوی اصلی",
    dashboard: "داشبورد",
    takeFreeChallenge: "شرکت در چالش رایگان",
    takePaidChallenge: "شرکت در چالش جدید",
    challenges: "چالش‌های من",
    challengesAdmin: "چالش‌ها",
    users: "کاربران",
    quickAccess: "دسترسی سریع",
    appRules: "قوانین",
    campaigns: "کمپین‌ها",
    challengeBalances: "بالانس اکانت‌ها",
    challengeLeverages: "اهرم‌ها",
    challengeServers: "سرورها",
    challengeRules: "قوانین",
    challengePlatforms: "پلتفرم‌ها",
    tickets: "تیکت‌های پشتیبانی",
    challengesManagement: "مدیریت چالش‌ها",
    verifyUserRequest: "احراز هویت",
    editProfile: "ویرایش پروفایل",
    changePassword: "تغییر کلمه عبور",
    logout: "خروج از حساب کاربری",
    telSupport: "تلفن پشتیبانی",
    tel: "09301234567",
    supportHours: "پاسخگوی تلفنی 9 صبح تا 9 شب",
    basicInformation: "اطلاعات پایه",
    villages: "روستاها",
    banks: "بانک ها",
    relationships: "روابط خویشاوندی",
    countries: "کشورها",
    services: "سرویس ها",
    exportLicense: "پروانه صادراتی",
    importLicense: "پروانه وارداتی",
    shareholders: "سهامداران",
};

export const dashboardPage = {
    _title: "داشبورد",
    _subTitle: "سامانه در یک نگاه",
    users: "کاربران",
    challenges: "چالش‌های برگزارشده",
};

export const usersPage = {
    _title: "کاربران",
    _subTitle: "فهرست کاربران سامانه",
    username: "نام کاربری",
    usernamePlaceholder: "نام کاربری",
    nameFamily: "نام / نام خانوادگی",
    nameFamilyPlaceholder: "نام / نام خانوادگی",
    email: "پست الکترونیک",
    emailPlaceholder: "پست الکترونیک",
    role: "نوع کاربری",
    status: "وضعیت",
    active: "فعال",
    notActive: "غیر فعال",
    addUser: "افزودن کاربر",
    searchSubmit: "جستجو",
    changePassword: "تغییر کلمه عبور",
    tickets: "تیکت‌ها",
    add: "افزودن کاربر",
};

export const addUserPage = {
    _title: "افزودن کاربر",
    _subTitle: "مشخصات کاربر جدید را وارد نمایید.",
    username: "نام کاربری",
    usernamePlaceholder: "نام کاربری",
    password: "کلمه عبور",
    confirmPassword: "تاییدیه کلمه عبور",
    name: "نام",
    namePlaceholder: "نام",
    family: "نام خانوادگی",
    familyPlaceholder: "نام خانوادگی",
    email: "پست الکترونیک",
    emailPlaceholder: "پست الکترونیک",
    status: "وضعیت",
    isActive: "فعال",
    type: "نوع کاربری",
    administrator: "مدیر",
    user: "کاربر",
    submitted: "افزودن کاربر با موفقیت انجام گردید.",
};

export const editUserPage = {
    _title: "ویرایش کاربر",
    _subTitle: "مشخصات کاربر تعریف‌شده را ویرایش نمایید.",
    name: "نام",
    namePlaceholder: "نام",
    family: "نام خانوادگی",
    familyPlaceholder: "نام خانوادگی",
    mobile: "موبایل",
    mobilePlaceholder: "موبایل",
    email: "پست الکترونیک",
    emailPlaceholder: "پست الکترونیک",
    status: "وضعیت",
    isActive: "فعال",
    type: "نوع کاربری",
    administrator: "مدیر",
    user: "کاربر",
    submitted: "ویرایش کاربر با موفقیت انجام گردید.",
};

export const editProfilePage = {
    _title: "ویرایش پروفایل",
    _subTitle: "مشخصات پروفایل خود را ویرایش نمایید.",
    name: "نام",
    namePlaceholder: "نام",
    family: "نام خانوادگی",
    familyPlaceholder: "نام خانوادگی",
    mobile: "موبایل",
    mobilePlaceholder: " موبایل",
    email: "پست الکترونیک",
    emailPlaceholder: "پست الکترونیک",
    status: "وضعیت",
    isActive: "فعال",
    type: "نوع کاربری",
    administrator: "مدیر",
    user: "کاربر",
    submitted: "ویرایش کاربر با موفقیت انجام گردید.",
};

export const changePasswordUserPage = {
    _title: "تغییر کلمه عبور",
    _subTitle: "لطفا کلمه عبور مورد نظر خود را وارد نمایید.",
    newPassword: "کلمه عبور جدید",
    newPasswordPlaceholder: "کلمه عبور جدید",
    confirmPassword: "تایید کلمه عبور جدید",
    confirmPasswordPlaceholder: "تایید کلمه عبور جدید",
    submitted: "تغییر کلمه عبور با موفقیت انجام گردید.",
};

export const genderTypes = {
    male: "مرد",
    female: "زن",
};

export const verifyUserPage = {
    _title: "احراز هویت",
    _subTitle: "لطفا اطلاعات هویتی خود را وارد نمایید.",
    title1: "اطلاعات فردی",
    name: "نام",
    namePlaceholder: "نام",
    family: "نام خانوادگی",
    familyPlaceholder: "نام خانوادگی",
    fatherName: "نام پدر",
    fatherNamePlaceholder: "نام پدر",
    nationalCode: "کد ملی",
    nationalCodePlaceholder: "کد ملی",
    identityNo: "شماره شناسنامه",
    identityNoPlaceholder: "شماره شناسنامه",
    birthDate: "تاریخ تولد",
    gender: "جنسیت",
    title2: "اطلاعات تماس",
    mobile: "موبایل",
    mobilePlaceholder: "موبایل",
    tel: "تلفن ثابت",
    telPlaceholder: "تلفن ثابت",
    email: "پست الکترونیک",
    emailPlaceholder: "پست الکترونیک",
    address: "آدرس",
    addressPlaceholder: "آدرس",
    title3: "تصویر سلفی",
    selfieFile: "پیوست سلفی",
    selfieFileProperties:
        "تصویر از خود به همراه مدرک شناسایی با فرمت jpg یا png و حداکثر سایز 4 مگابایت",
    selfieImage: "پیوست تصویر",
    selfieFileTips: "نکات پیوست سلفی",
    selfieFileDescription1:
        "عکسی از خود مطابق با تصویر نمونه، تهیه و ارسال کنید.",
    selfieFileDescription2:
        "* در صورتی که در حال حاضر امکان تهیه تصویر سلفی با مدرک شناسایی را ندارید، می‌توانید روی دکمه تکمیل اطلاعات بزنید و بعدا تصویر سلفی خود را ارسال کنید .",
    selfieFileDescription3:
        "طبق تصویر زیر، مدرک شناسایی خود را در دست نگه دارید. تصویر باید طوری باشد که مدرک شناسایی خوانا و چهره‌تان نمایان باشد.",
    title4: "تصویر مدرک شناسایی",
    identityFile: "پیوست مدرک شناسایی",
    identityFileProperties:
        "تصویری از مدرک شناسایی خود با فرمت jpg یا png و حداکثر سایز 4 مگابایت",
    identityImage: "پیوست تصویر",
    identityFileTips: "نکات پیوست تصویر مدرک شناسایی",
    identityFileDescription1:
        "عکسی از مدرک شناسایی خود مطابق با تصویر نمونه، تهیه و ارسال کنید.",
    identityFileDescription2:
        "* در صورتی که در حال حاضر امکان تهیه تصویر مدرک شناسایی  خود را ندارید، می‌توانید روی دکمه تکمیل اطلاعات بزنید و بعدا تصویر آن را ارسال کنید .",
    identityFileDescription3:
        "تصویر باید طوری باشد که مدرک شناسایی خوانا باشد.",
    submitted:
        "اطلاعات هویتی با موفقیت ثبت گردید. پس از تایید، می‌توانید در چالش شرکت نمایید.",
};

export const appRulesPage = {
    _title: "قوانین سایت",
    _subTitle: "فهرست قوانین سایت",
    title: "عنوان",
    body: "متن",
    add: "افزودن قانون",
};

export const addAppRulePage = {
    _title: "افزودن قانون",
    _subTitle: "قانون جدید را وارد نمایید.",
    title: "عنوان",
    titlePlaceholder: "عنوان",
    body: "متن",
    bodyPlaceholder: "متن",
    submitted: "افزودن قانون با موفقیت انجام گردید.",
};

export const editAppRulePage = {
    _title: "ویرایش قانون",
    _subTitle: "قانون تعریف‌شده را ویرایش نمایید.",
    title: "عنوان",
    titlePlaceholder: "عنوان",
    body: "متن",
    bodyPlaceholder: "متن",
    submitted: "ویرایش قانون با موفقیت انجام گردید.",
};

export const campaignsPage = {
    _title: "کمپین‌ها",
    _subTitle: "فهرست کمپین‌ها",
    title: "عنوان",
    status: "وضعیت",
    active: "فعال",
    notActive: "غیر فعال",
    add: "افزودن کمپین",
};

export const addCampaignPage = {
    _title: "افزودن کمپین",
    _subTitle: "مشخصات کمپین جدید را وارد نمایید.",
    title: "عنوان",
    titlePlaceholder: "عنوان",
    status: "وضعیت",
    isActive: "فعال",
    submitted: "افزودن کمپین با موفقیت انجام گردید.",
};

export const editCampaignPage = {
    _title: "ویرایش کمپین",
    _subTitle: "مشخصات کمپین تعریف‌شده را ویرایش نمایید.",
    title: "عنوان",
    titlePlaceholder: "عنوان",
    status: "وضعیت",
    isActive: "فعال",
    submitted: "ویرایش کمپین با موفقیت انجام گردید.",
};

export const ticketTypes = {
    type1: "مورد شکایت",
    type2: "پیشنهاد",
    type3: "اعلام خرابی",
    type4: "پشتیبانی فنی، مالی",
    type5: "سایر موارد",
};

export const addTicketPage = {
    _title: "ثبت تیکت",
    _subTitle: "",
    type: "نوع تیکت",
    subject: "موضوع",
    subjectPlaceholder: "موضوع",
    content: "متن",
    contentPlaceholder: "متن",
    file: "فایل پیوست (حداکثر حجم: 2 مگابایت)",
    submit: "ثبت",
    submitted: "ثبت تیکت با موفقیت انجام شد.",
    administratorTicketsError: "ارسال تیکت برای مدیر امکان‌پذیر نمی‌باشد.",
};

export const ticketThreadsPage = {
    _title: "مشاهده تیکت",
    _subTitle: "",
    sendTicket: "ارسال تیکت",
    content: "متن",
    file: "فایل ضمیمه",
    closeTicket: "بستن تیکت",
    submitted: "ثبت تیکت با موفقیت انجام شد.",
};

export const ticketsPage = {
    _title: "تیکت‌ها",
    _subTitle: "فهرست تیکت‌های پشتیبانی",
    add: "ثبت تیکت",
    user: "کاربر",
    type: "نوع",
    subject: "موضوع",
    new: "جدید",
    lastUpdate: "آخرین بروزرسانی",
    administratorTicketsError: "ارسال تیکت برای مدیر امکان‌پذیر نمی‌باشد.",
};

export const challengeServersPage = {
    _title: "سرورها",
    _subTitle: "فهرست سرورها",
    name: "نام سرور",
    title: "عنوان",
    add: "افزودن سرور",
};

export const addChallengeServerPage = {
    _title: "افزودن سرور",
    _subTitle: "سرور جدید را وارد نمایید.",
    name: "نام سرور",
    namePlaceholder: "نام سرور",
    title: "عنوان",
    titlePlaceholder: "عنوان",
    free: "استفاده در چالش رایگان",
    real: "استفاده در چالش غیر رایگان",
    submitted: "افزودن سرور با موفقیت انجام گردید.",
};

export const editChallengeServerPage = {
    _title: "ویرایش سرور",
    _subTitle: "مشخصات سرور را ویرایش نمایید.",
    name: "نام سرور",
    namePlaceholder: "نام سرور",
    title: "عنوان",
    titlePlaceholder: "عنوان",
    free: "استفاده در چالش رایگان",
    real: "استفاده در چالش غیر رایگان",
    submitted: "ویرایش سرور با موفقیت انجام گردید.",
};

export const challengeBalancesPage = {
    _title: "بالانس اکانت‌ها",
    _subTitle: "فهرست بالانس اکانت‌ها",
    value: "ارزش",
    add: "افزودن بالانس اکانت‌",
};

export const addChallengeBalancePage = {
    _title: "افزودن بالانس اکانت‌",
    _subTitle: "بالانس اکانت‌ جدید را وارد نمایید.",
    value: "ارزش",
    valuePlaceholder: "ارزش",
    free: "استفاده در چالش رایگان",
    real: "استفاده در چالش غیر رایگان",
    submitted: "افزودن بالانس اکانت‌ با موفقیت انجام گردید.",
};

export const editChallengeBalancePage = {
    _title: "ویرایش بالانس اکانت‌",
    _subTitle: "مشخصات بالانس اکانت‌ را ویرایش نمایید.",
    value: "ارزش",
    valuePlaceholder: "ارزش",
    free: "استفاده در چالش رایگان",
    real: "استفاده در چالش غیر رایگان",
    submitted: "ویرایش بالانس اکانت‌ با موفقیت انجام گردید.",
};

export const challengeLeveragesPage = {
    _title: "اهرم‌ها",
    _subTitle: "فهرست اهرم‌ها",
    value: "اهرم",
    add: "افزودن اهرم",
};

export const addChallengeLeveragePage = {
    _title: "افزودن اهرم",
    _subTitle: "اهرم جدید را وارد نمایید.",
    value: "اهرم",
    valuePlaceholder: "اهرم",
    free: "استفاده در چالش رایگان",
    real: "استفاده در چالش غیر رایگان",
    submitted: "افزودن اهرم با موفقیت انجام گردید.",
};

export const editChallengeLeveragePage = {
    _title: "ویرایش اهرم",
    _subTitle: "اهرم تعریف شده را ویرایش نمایید.",
    value: "اهرم",
    valuePlaceholder: "اهرم",
    free: "استفاده در چالش رایگان",
    real: "استفاده در چالش غیر رایگان",
    submitted: "ویرایش اهرم با موفقیت انجام گردید.",
};

export const challengeRulesPage = {
    _title: "قوانین چالش‌ها",
    _subTitle: "فهرست قوانین چالش‌ها",
    edit: "ویرایش قوانین چالش",
    level1: "مرحله اول",
    level2: "مرحله دوم",
    realAccount: "حساب Real",
    freeAccount: "چالش رایگان ",
    duration: "مدت زمان",
    dailySl: "حد ضرر روزانه",
    totalSl: "حد ضرر کلی",
    target: "تارگت سود",
    tradeDays: "حداقل روزهای ترید",
    noLimit: "نامحدود",
};

export const editChallengeRulePage = {
    _title: "ویرایش اهرم",
    _subTitle: "قوانین چالش تعریف شده را ویرایش نمایید.",
    duration1: "مدت زمان	(مرحله اول)",
    duration1Placeholder: "مدت زمان",
    duration2: "مدت زمان	(مرحله دوم)",
    duration2Placeholder: "مدت زمان",
    durationReal: "مدت زمان	(حساب Real)",
    durationRealPlaceholder: "مدت زمان",
    durationFree: "مدت زمان	(چالش رایگان)",
    durationFreePlaceholder: "مدت زمان",
    dailySl1: "حد ضرر روزانه	(مرحله اول)",
    dailySl1Placeholder: "حد ضرر روزانه",
    dailySl2: "حد ضرر روزانه	(مرحله دوم)",
    dailySl2Placeholder: "حد ضرر روزانه",
    dailySlReal: "حد ضرر روزانه	(حساب Real)",
    dailySlRealPlaceholder: "حد ضرر روزانه",
    dailySlFree: "حد ضرر روزانه	(چالش رایگان)",
    dailySlFreePlaceholder: "حد ضرر روزانه",
    totalSl1: "حد ضرر کلی	(مرحله اول)",
    totalSl1Placeholder: "حد ضرر کلی",
    totalSl2: "حد ضرر کلی	(مرحله دوم)",
    totalSl2Placeholder: "حد ضرر کلی",
    totalSlReal: "حد ضرر کلی	(حساب Real)",
    totalSlRealPlaceholder: "حد ضرر کلی",
    totalSlFree: "حد ضرر کلی	(چالش رایگان)",
    totalSlFreePlaceholder: "حد ضرر کلی",
    target1: "تارگت سود	(مرحله اول)",
    target1Placeholder: "تارگت سود",
    target2: "تارگت سود	(مرحله دوم)",
    target2Placeholder: "تارگت سود",
    targetReal: "تارگت سود	(حساب Real)",
    targetRealPlaceholder: "تارگت سود",
    targetFree: "تارگت سود	(چالش رایگان)",
    targetFreePlaceholder: "تارگت سود",
    tradeDays1: "حداقل روزهای ترید	(مرحله اول)",
    tradeDays1Placeholder: "حداقل روزهای ترید",
    tradeDays2: "حداقل روزهای ترید	(مرحله دوم)",
    tradeDays2Placeholder: "حداقل روزهای ترید",
    tradeDaysReal: "حداقل روزهای ترید	(حساب Real)",
    tradeDaysRealPlaceholder: "حداقل روزهای ترید",
    tradeDaysFree: "حداقل روزهای ترید (چالش رایگان)",
    tradeDaysFreePlaceholder: "حداقل روزهای ترید",
    submitted: "ویرایش قوانین چالش با موفقیت انجام گردید.",
};

export const challengePlatformsPage = {
    _title: "پلتفرم‌ها",
    _subTitle: "فهرست پلتفرم‌ها",
    value: "پلتفرم",
    add: "افزودن پلتفرم",
};

export const addChallengePlatformPage = {
    _title: "افزودن پلتفرم",
    _subTitle: "پلتفرم جدید را وارد نمایید.",
    value: "پلتفرم",
    valuePlaceholder: "پلتفرم",
    free: "استفاده در چالش رایگان",
    real: "استفاده در چالش غیر رایگان",
    submitted: "افزودن پلتفرم با موفقیت انجام گردید.",
};

export const editChallengePlatformPage = {
    _title: "ویرایش پلتفرم",
    _subTitle: "پلتفرم تعریف شده را ویرایش نمایید.",
    value: "پلتفرم",
    valuePlaceholder: "پلتفرم",
    free: "استفاده در چالش رایگان",
    real: "استفاده در چالش غیر رایگان",
    submitted: "ویرایش پلتفرم با موفقیت انجام گردید.",
};

export const takeChallenge = {
    balance: "بالانس اکانت",
    server: "انتخاب سرور",
    platform: "پلتفرم",
    leverage: "اهرم",
    level1: "مرحله اول",
    level2: "مرحله دوم",
    realAccount: "حساب Real",
    freeAccount: "چالش رایگان ",
    duration: "مدت زمان",
    dailySl: "حد ضرر روزانه",
    totalSl: "حد ضرر کلی",
    target: "تارگت سود",
    tradeDays: "حداقل روزهای ترید",
    noLimit: "نامحدود",
    rulesTitle: "قوانین و مقررات",
    rulesContent:
        "Due to the time-consuming nature of this document, some entrepreneurs may consider alternatives to a written agreement. Why not settle for an oral agreement instead? The trouble with an oral agreement, however, is in its name. The document isn’t in writing. You may struggle to recall the date of when a certain decision was made. However, a written agreement allows you to go back and review that specific moment in full detail. It’s also a helpful document for other owners of the business to look at and review if they have any questions. A written agreement may take a bit of time to write out and complete, but it is well worth the investment to ensure smooth operations.",
    register: "ثبت‌نام",
};

export const takeFreeChallengePage = {
    _title: "شرکت در چالش رایگان",
    _subTitle: "لطفا اطلاعات زیر را تکمیل نمایید.",
    submitted:
        "ثبت‌نام در چالش با موفقیت انجام گردید. ظرف حداکثر 10 دقیقه حساب شما فعال خواهد گردید.",
};

export const takeRealChallengePage = {
    _title: "شرکت در چالش جدید",
    _subTitle: "لطفا اطلاعات زیر را تکمیل نمایید.",
    submitted:
        "ثبت‌نام در چالش با موفقیت انجام گردید. ظرف حداکثر 10 دقیقه حساب شما فعال خواهد گردید.",
};

export const challengeStatuses = {
    waitingVerification: "در انتظار تایید",
    waitingTrade: "منتظر اولین ترید",
    trading: "در حال ترید",
    endChallenge: "پایان چالش",
};

export const challengesPage = {
    _title: "چالش‌ها",
    _titleUser: "چالش‌های من",
    _subTitle: "فهرست چالش‌ها",
    _subTitleUser: "فهرست چالش‌هایی که در آن شرکت کرده‌اید.",
    user: "کاربر",
    accountNo: "شماره حساب",
    status: "وضعیت",
    equity: "موجودی",
    server: "سرور",
    level: "چالش",
    analyze: "آنالیز",
    accountDetails: "جزییات حساب",
    password: "کلمه عبور",
    investorPassword: "کلمه عبور سرمایه‌گذار",
    metaApiToken: "Meta Api Token",
    metaApiAccountId: "Meta Api Account Id",
    changeStatus: "تغییر وضعیت",
    submitted: "وضعیت چالش با موفقیت تغییر یافت.",
};

export const editChallengePage = {
    _title: "مشخصات چالش",
    _subTitle: "نمایش مشخصات چالش",
    accountNo: "شماره حساب",
    password: "کلمه عبور",
    investorPassword: "کلمه عبور سرمایه‌گذار",
    metaApiToken: "Meta Api Token",
    metaApiAccountId: "Meta Api Account Id",
    status: "وضعیت",
    equity: "موجودی",
    server: "سرور",
    level: "چالش",
    submitted: "ویرایش مشخصات چالش با موفقیت انجام گردید.",
};

export const analyzeChallengePage = {
    _title: "گزارش حساب",
    _subTitle: "جزئیات حساب در یک نگاه",
    accountNo: "شماره حساب",
    platform: "پلتفرم",
    status: "وضعیت",
    accountType: "نوع اکانت",
    chart: "نمودار",
    balanceStartDay: "بالانس ابتدای روز",
    totalProfit: "سود ایجادشده",
    tradeDaysTitle: "حداقل :field روز ترید",
    tradeDaysBody:
        "برای پاس کردن این مرحله حداقل باید :field روز ترید انجام دهید.",
    maxDailyLoss: "حداکثر ضرر روزانه",
    maxTotalLoss: "حداکثر ضرر کلی",
    stable: "پایدار",
    accountDetails: "آمار جزییات معاملات",
    accountDetailsItem1: "تعداد معاملات",
    accountDetailsItem2: "معاملات موفق",
    accountDetailsItem3: "معاملات ناموفق",
    accountDetailsItem4: "میانگین زمان معاملات (دقیقه)",
    accountDetailsItem5: "برآیند پیپ معامله شده",
    accountDetailsItem6: "حجم معامله شده (لات)",
    accountDetailsItem7: "میانگین سود $",
    accountDetailsItem8: "میانگین سود (پیپ)",
    accountDetailsItem9: "میانگین ضرر $",
    accountDetailsItem10: "میانگین ضرر (پیپ)",
    accountDetailsItem11: "بهترین معامله $",
    accountDetailsItem12: "بهترین معامله (پیپ)",
    accountDetailsItem13: "بدترین معامله $",
    accountDetailsItem14: "بدترین معامله (پیپ)",
    parameteresTitle: "پارامترهای مدیریت ریسک",
    profitFactor: "profitFactor",
    sharpeRatio: "sharpeRatio",
    sortinoRatio: "sortinoRatio",
    zScore: "zScore",
    expectedProfit: "بازدهی مورد انتظار",
    expectedPipProfit: "بازدهی مورد انتظار بر اساس پیپ",
};
//  ganjineh

export const villagesPage = {
    _title: "روستاها",
    _subTitle: "فهرست روستاهای شهرستان تایباد",
    add: "افزودن روستا",
};

export const addvillagesPage = {
    _title: "افزودن روستا",
    _subTitle: "روستا جدید را وارد نمایید.",
    name: "نام",
    namePlaceholder: "نام",
    section: "	بخش",
    sectionPlaceholder: "بخش",
    village: "	روستا",
    villagePlaceholder: "روستا",
    real: "استفاده در چالش غیر رایگان",
    submitted: "افزودن روستا با موفقیت انجام گردید.",
};

export const editvillagesPage = {
    _title: "ویرایش روستا",
    _subTitle: "مشخصات روستا را ویرایش نمایید.",
    name: "نام",
    namePlaceholder: "نام",
    section: "	بخش",
    sectionPlaceholder: "بخش",
    village: "	روستا",
    villagePlaceholder: "روستا",
    real: "استفاده در چالش غیر رایگان",
    submitted: "ویرایش روستا با موفقیت انجام گردید.",
};
export const banksPage = {
    _title: "بانکها",
    _subTitle: "فهرست بانکهای شهرستان تایباد",
    add: "افزودن بانک",
};

export const addBanksPage = {
    _title: "افزودن بانک",
    _subTitle: "بانک جدید را وارد نمایید.",
    name: "نام",
    namePlaceholder: "نام",
    bank: "	بانک",
    bankPlaceholder: "بانک",
    real: "استفاده در چالش غیر رایگان",
    submitted: "افزودن بانک با موفقیت انجام گردید.",
};

export const editBanksPage = {
    _title: "ویرایش بانک",
    _subTitle: "مشخصات بانک را ویرایش نمایید.",
    name: "نام",
    namePlaceholder: "نام",
    bank: "	بانک",
    bankPlaceholder: "بانک",
    real: "استفاده در چالش غیر رایگان",
    submitted: "ویرایش بانک با موفقیت انجام گردید.",
};

export const relationshipsPage = {
    _title: "روابط خویشاوندی",
    _subTitle: "فهرست روابط خویشاوندی شهرستان تایباد",
    add: "افزودن رابطه خویشاوندی",
};

export const addRelationshipsPage = {
    _title: "افزودن رابطه خویشاوندی",
    _subTitle: "رابطه خویشاوندی جدید را وارد نمایید.",
    name: "نام",
    namePlaceholder: "نام",
    relationship: "	رابطه خویشاوندی",
    relationshipPlaceholder: "رابطه خویشاوندی",
    real: "استفاده در چالش غیر رایگان",
    submitted: "افزودن رابطه خویشاوندی با موفقیت انجام گردید.",
};

export const editRelationshipsPage = {
    _title: "ویرایش رابطه خویشاوندی",
    _subTitle: "مشخصات رابطه خویشاوندی را ویرایش نمایید.",
    name: "نام",
    namePlaceholder: "نام",
    relationship: "	رابطه خویشاوندی",
    relationshipPlaceholder: "رابطه خویشاوندی",
    real: "استفاده در چالش غیر رایگان",
    submitted: "ویرایش رابطه خویشاوندی با موفقیت انجام گردید.",
};

export const countriesPage = {
    _title: "کشورها",
    _subTitle: "فهرست کشورها شهرستان تایباد",
    add: "افزودن کشور",
};

export const addCountriesPage = {
    _title: "افزودن کشور",
    _subTitle: "کشور جدید را وارد نمایید.",
    name: "نام",
    namePlaceholder: "نام",
    country: "کشور",
    countryPlaceholder: "کشور",
    real: "استفاده در چالش غیر رایگان",
    submitted: "افزودن کشور با موفقیت انجام گردید.",
};

export const editCountriesPage = {
    _title: "ویرایش کشور",
    _subTitle: "مشخصات کشور را ویرایش نمایید.",
    name: "نام",
    namePlaceholder: "نام",
    country: "کشور",
    countryPlaceholder: "کشور",
    real: "استفاده در چالش غیر رایگان",
    submitted: "ویرایش کشور با موفقیت انجام گردید.",
};

export const exportLicensesPage = {
    _title: "پروانه صادراتی",
    _subTitle: "فهرست پروانه های صادراتی شهرستان تایباد",
    add: "افزودن پروانه صادراتی",
};

export const addExportLicensesPage = {
    _title: "افزودن پروانه صادراتی",
    _subTitle: "پروانه صادراتی جدید را وارد نمایید.",
    name: "نام",
    namePlaceholder: "نام",
    exportLicense: "پروانه صادراتی",
    exportLicensePlaceholder: "پروانه صادراتی",
    exportDeclaration: "اظهارنامه صادراتی",
    exportDeclarationPlaceholder: "اظهارنامه صادراتی",
    entrycustoms: "گمرک ورودی",
    entrycustomsPlaceholder: "گمرک ورودی",
    customsCode: "کد گمرک",
    customsCodePlaceholder: "کد گمرک",
    cottage: "کوتاژ",
    cottagePlaceholder: "کوتاژ",
    date: "تاریخ",
    datePlaceholder: "تاریخ",
    sheet: "برگه",
    sheetPlaceholder: "برگه",
    contents: "فهرست",
    contentsPlaceholder: "فهرست",
    items: "اقلام",
    itemsPlaceholder: "اقلام",
    numOfPackages: "تعداد بسته",
    numOfPackagesPlaceholder: "تعداد بسته",
    inflection: "عطف",
    inflectionPlaceholder: "عطف",
    archiveNo: "شماره بایگانی",
    archiveNoPlaceholder: "شماره بایگانی",
    manifest: "مانیفست",
    manifestPlaceholder: "مانیفست",
    exporter: "صادرکننده",
    exporterPlaceholder: "صادرکننده",
    productOwner: "مسئول تسویه مالی (صاحب کالا)",
    productOwnerPlaceholder: "مسئول تسویه مالی (صاحب کالا)",
    componentsOfValue: "اجزا ارزش",
    componentsOfValuePlaceholder: "اجزا ارزش",
    valueComponentCode: "کد اجزا ارزش",
    valueComponentCodePlaceholder: "کد اجزا ارزش",
    address: "آدرس",
    addressPlaceholder: "آدرس",
    phone: "تلفن",
    phonePlaceholder: "تلفن",
    freightNumber: "شماره بارنامه",
    freightNumberPlaceholder: "شماره بارنامه",
    declarantsRepresentative: "نماینده اظهارکننده",
    declarantsRepresentativePlaceholder: "نماینده اظهارکننده",
    workRights: "حق العمل کار",
    workRightsPlaceholder: "حق العمل کار",
    destinationCountry: "کشور مقصد",
    destinationCountryPlaceholder: "کشور مقصد",
    exportingCountry: "کشور صادرکننده",
    exportingCountryPlaceholder: "کشور صادرکننده",
    countryOfTransaction: "کشور طرف معامله",
    countryOfTransactionPlaceholder: "کشور طرف معامله",
    identityNationalityTransportArrival: "هویت و ملیت وسیله حمل در بدو ورود",
    identityNationalityTransportArrivalPlaceholder:
        "هویت و ملیت وسیله حمل در بدو ورود",
    identityNationalityTransportCrossing:
        "هویت و ملیت وسیله حمل در عبور از مرز",
    identityNationalityTransportCrossingPlaceholder:
        "هویت و ملیت وسیله حمل و نقل در عبور از مرز",
    FOBdeliveryTerms: "شرایط تحویل FOB",
    FOBdeliveryTermsPlaceholder: "شرایط تحویل FOB",
    country: "کشور",
    countryPlaceholder: "کشور",
    totalInvoiceAmount: "مبلغ کل فاکتور",
    totalInvoiceAmountPlaceholder: "مبلغ کل فاکتور",
    currency: "ارز",
    currencyPlaceholder: "ارز",
    exchangeRate: "نرخ ارز",
    exchangeRatePlaceholder: "نرخ ارز",
    transactionType: "نوع معامله",
    transactionTypePlaceholder: "نوع معامله",
    typeTransport: "نوع حمل",
    typeTransportPlaceholder: "نوع حمل",
    shippingCode: "کد حمل",
    shippingCodePlaceholder: "کد حمل",
    placeOfDischarge: "محل تخلیه",
    placeOfDischargePlaceholder: "محل تخلیه",
    ProvinceCode: "کد استان",
    ProvinceCodePlaceholder: "کد استان",
    financialBankingInfo: "اطلاعات مالی و بانکی",
    financialBankingInfoPlaceholder: "اطلاعات مالی و بانکی",
    bankCode: "کد بانک",
    bankCodePlaceholder: "کد بانک",
    paymentTerms: "شرایط پرداخت",
    paymentTermsPlaceholder: "شرایط پرداخت",
    bankName: "نام بانک",
    bankNamePlaceholder: "نام بانک",
    branch: "شعبه",
    branchPlaceholder: "شعبه",
    DocumentaryCreditNum: "شماره اعتباری اسنادی",
    DocumentaryCreditNumPlaceholder: "شماره اعتباری اسنادی",
    exitCustoms: "گمرک خروجی",
    exitCustomsPlaceholder: "گمرک خروجی",
    placeOfProductEvaluation: "محل ارزیابی کالا",
    placeOfProductEvaluationPlaceholder: "محل ارزیابی کالا",
    packagesPproductDesc: "بسته ها و شرح کالا",
    packagesPproductDescPlaceholder: "بسته ها و شرح کالا",
    orderRegistrationCode: "کد ثبت سفارش",
    orderRegistrationCodePlaceholder: "کد ثبت سفارش",
    brandType: "نوع برند",
    brandTypePlaceholder: "نوع برند",
    productModel: "مدل کالا",
    productModelPlaceholder: "مدل کالا",
    packageType: "نوع کالا",
    packageTypePlaceholder: "نوع کالا",
    warehouseReceiptNum: "شماره قبض انبار",
    warehouseReceiptNumPlaceholder: "شماره قبض انبار",
    warehouseTrackingNum: "شماره پیگیری انبار",
    warehouseTrackingNumPlaceholder: "شماره پیگیری انبار",
    descriptionOfGoods: "شرح کالا",
    descriptionOfGoodsPlaceholder: "شرح کالا",
    commercialDescriptionOfGoods: "شرح تجاری کالا",
    commercialDescriptionOfGoodsPlaceholder: "شرح تجاری کالا",
    ticketNum: "شماره قبض",
    ticketNumPlaceholder: "شماره قبض",
    productCode: "کد کالا",
    productCodePlaceholder: "کد کالا",
    manufacturingCountry: "کشور سازنده",
    manufacturingCountryPlaceholder: "کشور سازنده",
    grossWeight: "وزن ناخالص",
    grossWeightPlaceholder: "وزن ناخالص",
    source: "ماخذ",
    sourcePlaceholder: "ماخذ",
    insurance: "بیمه",
    insurancePlaceholder: "بیمه",
    rent: "کرایه",
    rentPlaceholder: "کرایه",
    netWeight: "وزن خالص",
    netWeightPlaceholder: "وزن خالص",
    NumOfUnitsOfGoods: "تعداد واحد کالا",
    NumOfUnitsOfGoodsPlaceholder: "تعداد واحد کالا",
    itemValue: "ارزش قلم کالا",
    itemValuePlaceholder: "ارزش قلم کالا",
    cloudy: "کدر",
    cloudyPlaceholder: "کدر",
    addDocuments: "اضافه اسناد",
    addDocumentsPlaceholder: "اضافه اسناد",
    discountPercent: "درصد تخفیف",
    discountPercentPlaceholder: "درصد تخفیف",
    interestRate: "نرخ سود",
    interestRatePlaceholder: "نرخ سود",
    salaryRate: "نرخ حقوق",
    salaryRatePlaceholder: "نرخ حقوق",
    attachedDocuments: "اسناد ضمیمه",
    attachedDocumentsPlaceholder: "اسناد ضمیمه",
    adjustmentRate: "نرخ تعدیل",
    adjustmentRatePlaceholder: "نرخ تعدیل",
    customsValueOfItem: "ارزش گمرکی قلم کالا",
    customsValueOfItemPlaceholder: "ارزش گمرکی قلم کالا",
    creditAccountCode: "کد حساب اعتباری",
    creditAccountCodePlaceholder: "کد حساب اعتباری",
    warehouseInfo: "اطلاعات انبار",
    warehouseInfoPlaceholder: "اطلاعات انبار",
    real: "استفاده در چالش غیر رایگان",
    submitted: "افزودن پروانه صادراتی با موفقیت انجام گردید.",
};

export const editExportLicensesPage = {
    _title: "ویرایش پروانه صادراتی",
    _subTitle: "مشخصات پروانه صادراتی را ویرایش نمایید.",
    name: "نام",
    namePlaceholder: "نام",
    exportLicense: "پروانه صادراتی",
    exportLicensePlaceholder: "پروانه صادراتی",
    real: "استفاده در چالش غیر رایگان",
    submitted: "ویرایش پروانه صادراتی با موفقیت انجام گردید.",
};

export const importLicensesPage = {
    _title: "پروانه وارداتی",
    _subTitle: "فهرست پروانه های وارداتی شهرستان تایباد",
    add: "افزودن پروانه وارداتی",
};

export const addImportLicensesPage = {
    _title: "افزودن پروانه وارداتی",
    _subTitle: "پروانه وارداتی جدید را وارد نمایید.",
    name: "نام",
    namePlaceholder: "نام",
    importLicense: "پروانه وارداتی",
    importLicensePlaceholder: "پروانه وارداتی",
    importDeclaration: "اظهارنامه وارداتی",
    importDeclarationPlaceholder: "اظهارنامه وارداتی",
    entrycustoms: "گمرک ورودی",
    entrycustomsPlaceholder: "گمرک ورودی",
    customsCode: "کد گمرک",
    customsCodePlaceholder: "کد گمرک",
    cottage: "کوتاژ",
    cottagePlaceholder: "کوتاژ",
    date: "تاریخ",
    datePlaceholder: "تاریخ",
    sheet: "برگه",
    sheetPlaceholder: "برگه",
    contents: "فهرست",
    contentsPlaceholder: "فهرست",
    items: "اقلام",
    itemsPlaceholder: "اقلام",
    numOfPackages: "تعداد بسته",
    numOfPackagesPlaceholder: "تعداد بسته",
    inflection: "عطف",
    inflectionPlaceholder: "عطف",
    archiveNo: "شماره بایگانی",
    archiveNoPlaceholder: "شماره بایگانی",
    manifest: "مانیفست",
    manifestPlaceholder: "مانیفست",
    exporter: "صادرکننده",
    exporterPlaceholder: "صادرکننده",
    productOwner: "مسئول تسویه مالی (صاحب کالا)",
    productOwnerPlaceholder: "مسئول تسویه مالی (صاحب کالا)",
    componentsOfValue: "اجزا ارزش",
    componentsOfValuePlaceholder: "اجزا ارزش",
    valueComponentCode: "کد اجزا ارزش",
    valueComponentCodePlaceholder: "کد اجزا ارزش",
    address: "آدرس",
    addressPlaceholder: "آدرس",
    phone: "تلفن",
    phonePlaceholder: "تلفن",
    freightNumber: "شماره بارنامه",
    freightNumberPlaceholder: "شماره بارنامه",
    declarantsRepresentative: "نماینده اظهارکننده",
    declarantsRepresentativePlaceholder: "نماینده اظهارکننده",
    workRights: "حق العمل کار",
    workRightsPlaceholder: "حق العمل کار",
    destinationCountry: "کشور مقصد",
    destinationCountryPlaceholder: "کشور مقصد",
    exportingCountry: "کشور صادرکننده",
    exportingCountryPlaceholder: "کشور صادرکننده",
    countryOfTransaction: "کشور طرف معامله",
    countryOfTransactionPlaceholder: "کشور طرف معامله",
    identityNationalityTransportArrival: "هویت و ملیت وسیله حمل در بدو ورود",
    identityNationalityTransportArrivalPlaceholder:
        "هویت و ملیت وسیله حمل در بدو ورود",
    identityNationalityTransportCrossing:
        "هویت و ملیت وسیله حمل در عبور از مرز",
    identityNationalityTransportCrossingPlaceholder:
        "هویت و ملیت وسیله حمل و نقل در عبور از مرز",
    FOBdeliveryTerms: "شرایط تحویل FOB",
    FOBdeliveryTermsPlaceholder: "شرایط تحویل FOB",
    country: "کشور",
    countryPlaceholder: "کشور",
    totalInvoiceAmount: "مبلغ کل فاکتور",
    totalInvoiceAmountPlaceholder: "مبلغ کل فاکتور",
    currency: "ارز",
    currencyPlaceholder: "ارز",
    exchangeRate: "نرخ ارز",
    exchangeRatePlaceholder: "نرخ ارز",
    transactionType: "نوع معامله",
    transactionTypePlaceholder: "نوع معامله",
    typeTransport: "نوع حمل",
    typeTransportPlaceholder: "نوع حمل",
    shippingCode: "کد حمل",
    shippingCodePlaceholder: "کد حمل",
    placeOfDischarge: "محل تخلیه",
    placeOfDischargePlaceholder: "محل تخلیه",
    ProvinceCode: "کد استان",
    ProvinceCodePlaceholder: "کد استان",
    financialBankingInfo: "اطلاعات مالی و بانکی",
    financialBankingInfoPlaceholder: "اطلاعات مالی و بانکی",
    bankCode: "کد بانک",
    bankCodePlaceholder: "کد بانک",
    paymentTerms: "شرایط پرداخت",
    paymentTermsPlaceholder: "شرایط پرداخت",
    bankName: "نام بانک",
    bankNamePlaceholder: "نام بانک",
    branch: "شعبه",
    branchPlaceholder: "شعبه",
    DocumentaryCreditNum: "شماره اعتباری اسنادی",
    DocumentaryCreditNumPlaceholder: "شماره اعتباری اسنادی",
    exitCustoms: "گمرک خروجی",
    exitCustomsPlaceholder: "گمرک خروجی",
    placeOfProductEvaluation: "محل ارزیابی کالا",
    placeOfProductEvaluationPlaceholder: "محل ارزیابی کالا",
    packagesPproductDesc: "بسته ها و شرح کالا",
    packagesPproductDescPlaceholder: "بسته ها و شرح کالا",
    orderRegistrationCode: "کد ثبت سفارش",
    orderRegistrationCodePlaceholder: "کد ثبت سفارش",
    brandType: "نوع برند",
    brandTypePlaceholder: "نوع برند",
    productModel: "مدل کالا",
    productModelPlaceholder: "مدل کالا",
    packageType: "نوع کالا",
    packageTypePlaceholder: "نوع کالا",
    warehouseReceiptNum: "شماره قبض انبار",
    warehouseReceiptNumPlaceholder: "شماره قبض انبار",
    warehouseTrackingNum: "شماره پیگیری انبار",
    warehouseTrackingNumPlaceholder: "شماره پیگیری انبار",
    descriptionOfGoods: "شرح کالا",
    descriptionOfGoodsPlaceholder: "شرح کالا",
    commercialDescriptionOfGoods: "شرح تجاری کالا",
    commercialDescriptionOfGoodsPlaceholder: "شرح تجاری کالا",
    ticketNum: "شماره قبض",
    ticketNumPlaceholder: "شماره قبض",
    productCode: "کد کالا",
    productCodePlaceholder: "کد کالا",
    manufacturingCountry: "کشور سازنده",
    manufacturingCountryPlaceholder: "کشور سازنده",
    grossWeight: "وزن ناخالص",
    grossWeightPlaceholder: "وزن ناخالص",
    source: "ماخذ",
    sourcePlaceholder: "ماخذ",
    insurance: "بیمه",
    insurancePlaceholder: "بیمه",
    rent: "کرایه",
    rentPlaceholder: "کرایه",
    netWeight: "وزن خالص",
    netWeightPlaceholder: "وزن خالص",
    NumOfUnitsOfGoods: "تعداد واحد کالا",
    NumOfUnitsOfGoodsPlaceholder: "تعداد واحد کالا",
    itemValue: "ارزش قلم کالا",
    itemValuePlaceholder: "ارزش قلم کالا",
    cloudy: "کدر",
    cloudyPlaceholder: "کدر",
    addDocuments: "اضافه اسناد",
    addDocumentsPlaceholder: "اضافه اسناد",
    discountPercent: "درصد تخفیف",
    discountPercentPlaceholder: "درصد تخفیف",
    interestRate: "نرخ سود",
    interestRatePlaceholder: "نرخ سود",
    salaryRate: "نرخ حقوق",
    salaryRatePlaceholder: "نرخ حقوق",
    attachedDocuments: "اسناد ضمیمه",
    attachedDocumentsPlaceholder: "اسناد ضمیمه",
    adjustmentRate: "نرخ تعدیل",
    adjustmentRatePlaceholder: "نرخ تعدیل",
    customsValueOfItem: "ارزش گمرکی قلم کالا",
    customsValueOfItemPlaceholder: "ارزش گمرکی قلم کالا",
    creditAccountCode: "کد حساب اعتباری",
    creditAccountCodePlaceholder: "کد حساب اعتباری",
    warehouseInfo: "اطلاعات انبار",
    warehouseInfoPlaceholder: "اطلاعات انبار",
    real: "استفاده در چالش غیر رایگان",
    submitted: "افزودن پروانه وارداتی با موفقیت انجام گردید.",
};

export const editImportLicensesPage = {
    _title: "ویرایش پروانه وارداتی",
    _subTitle: "مشخصات پروانه وارداتی را ویرایش نمایید.",
    name: "نام",
    namePlaceholder: "نام",
    exportLicense: "پروانه وارداتی",
    exportLicensePlaceholder: "پروانه وارداتی",
    real: "استفاده در چالش غیر رایگان",
    submitted: "ویرایش پروانه وارداتی با موفقیت انجام گردید.",
};

export const shareholdersPage = {
    _title: "سهامداران",
    _subTitle: "فهرست سهامداران شهرستان تایباد",
    add: "افزودن سهامدار",
};

export const addShareholdersPage = {
    _title: "افزودن سهامدار",
    _subTitle: "سهامدار جدید را وارد نمایید.",
    name: "نام",
    namePlaceholder: "نام",
    family: "نام خانوادگی",
    familyPlaceholder: "نام خانوادگی",
    fatherName: "نام پدر",
    fatherNamePlaceholder: "نام پدر",
    nationalCode: "کد ملی",
    nationalCodePlaceholder: "کد ملی",
    identityNo: "شماره شناسنامه",
    identityNoPlaceholder: "شماره شناسنامه",
    mobile: "موبایل",
    mobilePlaceholder: "موبایل",
    village: "روستا",
    villagePlaceholder: "روستا",
    villageTwo: "دهستان",
    villageTwoPlaceholder: "دهستان",
    postalCode: "کد پستی",
    postalCodePlaceholder: "کد پستی",
    description: "توضیحات",
    descriptionPlaceholder: "توضیحات",
    birthDate: "تاریخ تولد",
    registeryDate: "تاریخ عضویت",
    gender: "جنسیت",
    tel: "تلفن ثابت",
    telPlaceholder: "تلفن ثابت",
    address: "آدرس",
    addressPlaceholder: "آدرس",
    accountNum: "شماره حساب",
    accountNumPlaceholder: "شماره حساب",
    receiptNumber: "شماره فیش",
    receiptNumberPlaceholder: "شماره فیش",
    dateOfDeposit: "تاریخ واریز",
    dateOfDepositPlaceholder: "تاریخ واریز",
    bankName: "نام بانک",
    bankNamePlaceholder: "نام بانک",
    shareholder: "سهامدار",
    shareholderPlaceholder: "سهامدار",
    real: "استفاده در چالش غیر رایگان",
    submitted: "افزودن سهامدار با موفقیت انجام گردید.",

};

export const editShareholdersPage = {
    _title: "ویرایش سهامدار",
    _subTitle: "مشخصات سهامدار را ویرایش نمایید.",
    name: "نام",
    namePlaceholder: "نام",
    family: "نام خانوادگی",
    familyPlaceholder: "نام خانوادگی",
    fatherName: "نام پدر",
    fatherNamePlaceholder: "نام پدر",
    nationalCode: "کد ملی",
    nationalCodePlaceholder: "کد ملی",
    identityNo: "شماره شناسنامه",
    identityNoPlaceholder: "شماره شناسنامه",
    mobile: "موبایل",
    mobilePlaceholder: "موبایل",
    village: "روستا",
    villagePlaceholder: "روستا",
    villageTwo: "دهستان",
    villageTwoPlaceholder: "دهستان",
    postalCode: "کد پستی",
    postalCodePlaceholder: "کد پستی",
    description: "توضیحات",
    descriptionPlaceholder: "توضیحات",
    birthDate: "تاریخ تولد",
    registeryDate: "تاریخ عضویت",
    gender: "جنسیت",
    tel: "تلفن ثابت",
    telPlaceholder: "تلفن ثابت",
    address: "آدرس",
    addressPlaceholder: "آدرس",
    accountNum: "شماره حساب",
    accountNumPlaceholder: "شماره حساب",
    receiptNumber: "شماره فیش",
    receiptNumberPlaceholder: "شماره فیش",
    dateOfDeposit: "تاریخ واریز",
    dateOfDepositPlaceholder: "تاریخ واریز",
    bankName: "نام بانک",
    bankNamePlaceholder: "نام بانک",
    shareholder: "سهامدار",
    shareholderPlaceholder: "سهامدار",
    real: "استفاده در چالش غیر رایگان",
    submitted: "ویرایش سهامدار با موفقیت انجام گردید.",
};

export const shareholderRelationshipsPage = {
    _title: "افراد تحت تکفل",
    _subTitle: "فهرست افراد تحت تکفل شهرستان تایباد",
    add: "افزودن فرد تحت تکفل",
};

export const addShareholderRelationshipsPage = {
    _title: "افزودن فرد تحت تکفل",
    _subTitle: "فرد تحت تکفل جدید را وارد نمایید.",
    name: "نام",
    namePlaceholder: "نام",
    family: "نام خانوادگی",
    familyPlaceholder: "نام خانوادگی",
    nationalCode: "کد ملی",
    nationalCodePlaceholder: "کد ملی",
    identityNo: "شماره شناسنامه",
    identityNoPlaceholder: "شماره شناسنامه",
    mobile: "موبایل",
    mobilePlaceholder: "موبایل",
    description: "توضیحات",
    descriptionPlaceholder: "توضیحات",
    birthDate: "تاریخ تولد",
    gender: "جنسیت",
    tel: "تلفن ثابت",
    telPlaceholder: "تلفن ثابت",
    address: "آدرس",
    addressPlaceholder: "آدرس",
    shareholderRelationship: "نسبت",
    shareholderRelationshipPlaceholder: "نسبت",
    real: "استفاده در چالش غیر رایگان",
    submitted: "افزودن فرد تحت تکفل با موفقیت انجام گردید.",
};

export const editShareholderRelationshipsPage = {
    _title: "ویرایش فرد تحت تکفل",
    _subTitle: "مشخصات فرد تحت تکفل را ویرایش نمایید.",
    name: "نام",
    namePlaceholder: "نام",
    family: "نام خانوادگی",
    familyPlaceholder: "نام خانوادگی",
    nationalCode: "کد ملی",
    nationalCodePlaceholder: "کد ملی",
    identityNo: "شماره شناسنامه",
    identityNoPlaceholder: "شماره شناسنامه",
    mobile: "موبایل",
    mobilePlaceholder: "موبایل",
    description: "توضیحات",
    descriptionPlaceholder: "توضیحات",
    birthDate: "تاریخ تولد",
    gender: "جنسیت",
    tel: "تلفن ثابت",
    telPlaceholder: "تلفن ثابت",
    address: "آدرس",
    addressPlaceholder: "آدرس",
    shareholderRelationship: "نسبت",
    shareholderRelationshipPlaceholder: "نسبت",
    real: "استفاده در چالش غیر رایگان",
    submitted: "ویرایش فرد تحت تکفل با موفقیت انجام گردید.",
};
