import React from "react";

import { InputTextColumn, FormPage, InputRow } from "../../../components";
import { PageUtils } from "./PageUtils";

const EditChallengeRule = () => {
  const pageUtils = new PageUtils();

  return (
    <FormPage pageUtils={pageUtils}>
      <InputRow>
        <InputTextColumn
          field="duration1"
          textAlign="left"
          type="number"
          showLabel
          fullRow={false}
        />
        <InputTextColumn
          field="duration2"
          textAlign="left"
          type="number"
          showLabel
          fullRow={false}
        />
        <InputTextColumn
          field="durationReal"
          textAlign="left"
          type="number"
          showLabel
          fullRow={false}
        />
        <InputTextColumn
          field="durationFree"
          textAlign="left"
          type="number"
          showLabel
          fullRow={false}
        />
      </InputRow>
      <InputRow>
        <InputTextColumn
          field="dailySl1"
          textAlign="left"
          type="number"
          showLabel
          fullRow={false}
        />
        <InputTextColumn
          field="dailySl2"
          textAlign="left"
          type="number"
          showLabel
          fullRow={false}
        />
        <InputTextColumn
          field="dailySlReal"
          textAlign="left"
          type="number"
          showLabel
          fullRow={false}
        />
        <InputTextColumn
          field="dailySlFree"
          textAlign="left"
          type="number"
          showLabel
          fullRow={false}
        />
      </InputRow>
      <InputRow>
        <InputTextColumn
          field="totalSl1"
          textAlign="left"
          type="number"
          showLabel
          fullRow={false}
        />
        <InputTextColumn
          field="totalSl2"
          textAlign="left"
          type="number"
          showLabel
          fullRow={false}
        />
        <InputTextColumn
          field="totalSlReal"
          textAlign="left"
          type="number"
          showLabel
          fullRow={false}
        />
        <InputTextColumn
          field="totalSlFree"
          textAlign="left"
          type="number"
          showLabel
          fullRow={false}
        />
      </InputRow>
      <InputRow>
        <InputTextColumn
          field="target1"
          textAlign="left"
          type="number"
          showLabel
          fullRow={false}
        />
        <InputTextColumn
          field="target2"
          textAlign="left"
          type="number"
          showLabel
          fullRow={false}
        />
        <InputTextColumn
          field="targetReal"
          textAlign="left"
          type="number"
          showLabel
          fullRow={false}
        />
        <InputTextColumn
          field="targetFree"
          textAlign="left"
          type="number"
          showLabel
          fullRow={false}
        />
      </InputRow>
      <InputRow>
        <InputTextColumn
          field="tradeDays1"
          textAlign="left"
          type="number"
          showLabel
          fullRow={false}
        />
        <InputTextColumn
          field="tradeDays2"
          textAlign="left"
          type="number"
          showLabel
          fullRow={false}
        />
        <InputTextColumn
          field="tradeDaysReal"
          textAlign="left"
          type="number"
          showLabel
          fullRow={false}
        />
        <InputTextColumn
          field="tradeDaysFree"
          textAlign="left"
          type="number"
          showLabel
          fullRow={false}
        />
      </InputRow>
    </FormPage>
  );
};

export default EditChallengeRule;
